#!/bin/bash

echo "开始检查编码规范..."

lint_failed=false
version="--cached"

for file in $(git diff $version --name-only | grep -E 'src/.*\.(tsx?)$' | grep -v '.test.ts')
do
  echo "lint file ===== $file"
	# git show ":$file" | node_modules/.bin/tslint --project tsconfig.json --config tslint.js --fix "$file"
	# if [[ "$file" != "src/component/workflow-manage/common/eCharts/index.tsx" ]]; then
  git show ":$file" | node_modules/.bin/tslint --project tsconfig.json --config tslint.js --fix "$file"
	# fi

  if [ $? -ne 0 ]; then
  	lint_failed=true
	echo "TSLint检查失败：'$file'. 请检查代码并重试."
	break
  fi
done

if $lint_failed; then
	exit 1
else
	echo "代码符合规范！"
fi